Repository sakibguy/Telethon, pull requests merged in 2021-08, with the labels that each got.

#9 Expose more raw API params in friendly methods (#3104)
  telethon/client/messages.py
  telethon/client/uploads.py
  telethon/tl/custom/button.py
  telethon/tl/custom/inlineresult.py
Labels: documentation, enhancement

#10 Allow per-request flood sleep threshold selection (#3123)
  telethon/client/telegrambaseclient.py
  telethon/client/users.py
Labels: bug

#11 Fix add_admins property of custom.ParticipantPermissions (#3132)
  telethon/tl/custom/participantpermissions.py
Labels: bug

#12 Add new known RPC errors (#3134)
  telethon_generator/data/errors.csv
  telethon_generator/data/methods.csv
Labels: documentation
